INSERT INTO MPA_RATING (MPA_RATING_ID, NAME)
VALUES (1, 'G');

INSERT INTO MPA_RATING (MPA_RATING_ID, NAME)
VALUES (2, 'PG');

INSERT INTO MPA_RATING (MPA_RATING_ID, NAME)
VALUES (3, 'PG-13');

INSERT INTO MPA_RATING (MPA_RATING_ID, NAME)
VALUES (4, 'R');

INSERT INTO MPA_RATING (MPA_RATING_ID, NAME)
VALUES (5, 'NC-17');


INSERT INTO GENRES (GENRE_NAME)
VALUES ('Комедия');

INSERT INTO GENRES (GENRE_NAME)
VALUES ('Драма');

INSERT INTO GENRES (GENRE_NAME)
VALUES ('Мультфильм');

INSERT INTO GENRES (GENRE_NAME)
VALUES ('Триллер');

INSERT INTO GENRES (GENRE_NAME)
VALUES ('Документальный');

INSERT INTO GENRES (GENRE_NAME)
VALUES ('Боевик');








